site_name: Modules Documentation
repo_name: Ozzypig/Modules
repo_url: https://github.com/Ozzypig/Modules

theme:
  name: material #readthedocs
  palette:
    priamry: 'Red'
    accent: 'Red'

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Modules:
    - 'ModuleLoader': api/ModuleLoader.md
    - 'class': api/class.md
  - Classes:
    - 'Maid': api/Maid.md
    - 'Event': api/Event.md
    - 'StateMachine': api/StateMachine.md
    - 'State': api/State.md

docs_dir: docs-build

extra_css: [extra.css]

markdown_extensions:
  - toc
